add nodepool autonomy into yurt-manager
openyurtio/openyurt pull request #1322
Opened 2023-03-21 07:29 UTC by JameKeal

#### What type of PR is this?
> Uncomment only one `/kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind bug
> /kind documentation
> /kind enhancement
> /kind good-first-issue
> /kind feature
> /kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage

 /kind feature

#### What this PR does / why we need it:

On the current situation, when nodepool disconnect with cloud, if node does not open autonomy, the pod in node wil be evict. In another way, if the node open autonomy, when node actually down, the pod binding controller will not evict the pod, it`s different from nodepool governance.

#### Which issue(s) this PR fixes:

Fixes https://github.com/openyurtio/openyurt/issues/1197

#### Special notes for your reviewer:

/assign @rambohe-ch

#### Does this PR introduce a user-facing change?

```release-note

```

#### other Note

2023-03-21 08:27 UTC, rambohe-ch commented
@JameKeal please fix golangci-lint errors.

2023-03-21 09:19 UTC, fengshunli requested changes
```suggestion
// Cluster implements a validating and defaulting webhook for Cluster.
```

PodHandler

2023-04-12 01:45 UTC, JameKeal commented on pkg/webhook/pod/v1/pod_validation.go
> +	if err := cli.Get(context.TODO(), client.ObjectKey{Name: nodeName}, &node); err != nil {
That client has a cache, once you request a resource, it parses it out of scheme, it automatically triggers the informer thing, and then it goes into the cache and then your get goes out of the cache.

The controller-runtime code show as follows.
![image](https://user-images.githubusercontent.com/70508195/231325885-a976b122-7ad3-471e-9fad-514b5eb69a5f.png)

![image](https://user-images.githubusercontent.com/70508195/231325438-bea01b3c-7850-4c9e-b61f-fc77d2173758.png)

2023-04-12 02:18 UTC, rambohe-ch commented on pkg/webhook/pod/v1/pod_default.go
> +/*
It seems that `mutate webhook` is not needed for nodepool autonomy, so how about remove this webhook for improving webhook efficiency?

2023-04-12 02:32 UTC, rambohe-ch commented on pkg/webhook/pod/v1/pod_handler.go
> +// SetupWebhookWithManager sets up Cluster webhooks. 	mutate path, validatepath, error
we need to add some RBAC rules for this webhook, for example: list/watch/get nodepool, node, lease resource.

2023-04-12 07:57 UTC, rambohe-ch commented on pkg/webhook/pod/v1/pod_handler.go
> +// SetupWebhookWithManager sets up Cluster webhooks. 	mutate path, validatepath, error
ok

2023-04-12 09:58 UTC, rambohe-ch commented on pkg/webhook/pod/v1/pod_handler.go
> +// +kubebuilder:webhook:path=/validate-core-openyurt-io-pod,mutating=false,failurePolicy=fail,sideEffects=None,admissionReviewVersions=v1;v1beta1,groups=core.openyurt.io,resources=pods,verbs=delete,v
path should be `/validate-core-openyurt-io-v1-pod` instead of `/validate-core-openyurt-io-pod`

2023-04-12 09:58 UTC, rambohe-ch commented on charts/openyurt/templates/yurt-manager-auto-generated.yaml
> +      path: /validate-core-openyurt-io-pod
path should be /validate-core-openyurt-io-v1-pod instead of /validate-core-openyurt-io-pod

2023-04-13 01:26 UTC, rambohe-ch approved these changes

2023-04-13 01:27 UTC, rambohe-ch commented
/lgtm

2023-04-13 01:27 UTC, merged