Features/dns controller
openyurtio/openyurt pull request #1594
Opened 2023-07-10 02:39 UTC by River-sh

#### What type of PR is this?
> Uncomment only one `/kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind enhancement
> /kind feature
> /sig network

#### What this PR does / why we need it:
The DNS Controller maintains a record of the NodeName mapping to the Raven L7 Proxy IP address in a configmap and mounts it into CoreDNS to support cross pool communication

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### other Note

2023-07-10 11:23 UTC, fengshunli requested changes

2023-07-10 11:23 UTC, fengshunli commented on pkg/controller/raven/dns/dns_controller.go
> +	for _, addr := range node.Status.Addresses {
reuse the same for loop, add else if to handle the same logic, reduce redundant code

2023-07-10 11:25 UTC, fengshunli commented on pkg/controller/apis/config/types.go
> +	GatewayController gatewayconfig.GatewayPickupControllerConfiguration
renmae GatewayPickupController

2023-07-10 11:27 UTC, fengshunli commented on cmd/yurt-manager/app/options/ravendnscontroller.go
> +		return nil
return err

2023-07-10 11:29 UTC, fengshunli requested changes

2023-07-10 11:29 UTC, fengshunli commented on pkg/controller/raven/dns/dns_controller.go
> +	return allIPs[0].String(), nil
add nil value judgment

2023-07-17 03:49 UTC, rambohe-ch commented
@River-sh I think it is not a good idea to add several controllers in only one pull request.  because it is not easy to review so much code in only one pull request. would you like to split this pull request and post one controller one by one?

2023-08-11 05:37 UTC, closed without merging