feat: establish the component mechanism of the iot system
openyurtio/openyurt pull request #1650
Opened 2023-08-12 06:41 UTC by LavenderQAQ

#### What type of PR is this?
/kind feature
/sig iot

#### What this PR does / why we need it:
Build PlatformAdmin's component mechanism to allow users to deploy common edgex extensions by simply filling in the component name.

#### Which issue(s) this PR fixes:

Fixes #1611

2023-08-13 07:34 UTC, LavenderQAQ commented
This pr is done, but it needs to wait for #1647 to merge.

2023-08-13 07:34 UTC, LavenderQAQ commented
/hold

2023-08-13 07:35 UTC, LavenderQAQ commented
@wangxye @Rui-Gan Please review it for me.

2023-08-13 07:36 UTC, LavenderQAQ commented
/assign @wangxye @Rui-Gan

2023-08-14 02:38 UTC, LavenderQAQ commented
/unhold

2023-08-14 02:38 UTC, LavenderQAQ commented
This pr is ready.

2023-08-16 06:47 UTC, Rui-Gan commented on pkg/controller/platformadmin/config/EdgeXConfig/manifest.yaml
> +  - edgex-core-metadata
Do we need to add the core-common-config-bootstrapper service?

2023-08-16 14:12 UTC, Rui-Gan commented
/assign

2023-08-16 14:14 UTC, Rui-Gan requested changes

2023-08-16 14:14 UTC, Rui-Gan commented on pkg/controller/platformadmin/config/EdgeXConfig/manifest.yaml
> +  - edgex-core-metadata
After discussion, this component needs to be added.

2023-08-17 03:09 UTC, Rui-Gan commented
/lgtm

2023-08-17 04:05 UTC, Rui-Gan approved these changes

2023-08-17 06:55 UTC, rambohe-ch approved these changes

2023-08-21 09:08 UTC, rambohe-ch approved these changes

2023-08-21 09:08 UTC, rambohe-ch commented
/lgtm

2023-08-21 09:09 UTC, merged