fix: add the logic of removing the finalizer
openyurtio/openyurt pull request #1695
Opened 2023-09-07 08:26 UTC by Pluviophile225

#### What type of PR is this?
/kind bug
/sig iot

#### What this PR does / why we need it:
add the logic of removing the finalizer
#### Which issue(s) this PR fixes:

Fixes #1694 

#### Special notes for your reviewer:

/assgin @LavenderQAQ @wangxye

2023-09-07 08:28 UTC, LavenderQAQ commented
/assign

2023-09-07 08:33 UTC, LavenderQAQ requested changes

2023-09-07 08:33 UTC, LavenderQAQ commented on pkg/yurtiotdock/controllers/deviceservice_syncer.go
> +			return err
Add the log before returning the error:
```go
klog.V(5).ErrorS(err, "fail to remove finalizer of DeviceService on Kubernetes", "DeviceService", kds.Name)
```

2023-09-07 08:33 UTC, LavenderQAQ commented on pkg/yurtiotdock/controllers/deviceprofile_syncer.go
> +			return err
Add the log before returning the error:
```go
klog.V(5).ErrorS(err, "fail to remove finalizer of DeviceProfile on Kubernetes", "DeviceProfile", dps.Name)
```

2023-09-07 08:33 UTC, LavenderQAQ commented on pkg/yurtiotdock/controllers/device_syncer.go
> +			return err
Add the log before returning the error:
```go
klog.V(5).ErrorS(err, "fail to remove finalizer of Device on Kubernetes", "Device", ds.Name)
```

2023-09-07 10:10 UTC, LavenderQAQ approved these changes
/lgtm

2023-09-08 03:06 UTC, LavenderQAQ commented
PTAL @wangxye

2023-09-08 09:46 UTC, wangxye commented
/assign

2023-09-14 05:45 UTC, rambohe-ch approved these changes

2023-09-14 05:46 UTC, rambohe-ch commented
/lgtm

2023-09-14 05:46 UTC, rambohe-ch commented
/approve

2023-09-14 06:45 UTC, merged