When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.
openyurtio/openyurt pull request #558
Opened 2021-11-05 08:50 UTC by yanyhui

#### What type of PR is this?
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind bug
> /kind documentation
> /kind enhancement
> /kind good-first-issue
> /kind feature
> /kind question
> /kind design
> /sig ai
> /sig iot
> /sig network
> /sig storage
> /sig storage

/kind bug
#### What this PR does / why we need it:
Yurtappmanager does not use the method of deleting crd resources when crd is not deployed.
#### Which issue(s) this PR fixes:

Fixes #557 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note

```

#### other Note

2021-11-05 09:10 UTC, adamzhoul requested changes

2021-11-05 09:10 UTC, adamzhoul commented on pkg/yurtctl/cmd/revert/revert.go
> -	klog.Info("deployment for yurt app manager is removed")
why do you think, we should remove that klog.Info?
same below.

2021-11-05 09:10 UTC, adamzhoul commented on pkg/yurtctl/cmd/revert/revert.go
> -	klog.Info("UnitedDeploymentcrd for yurt app manager is removed")
removeYurtAppManager方法  -> removeYurtAppManager ?

2021-11-05 09:10 UTC, adamzhoul commented on pkg/yurtctl/util/kubernetes/util.go
> +		klog.Info("不存在 " + name + " 这种crd资源，不需要删除")
use English only?

2021-11-08 08:32 UTC, adamzhoul commented
/lgtm

2021-11-08 08:53 UTC, rambohe-ch commented on pkg/yurtctl/util/kubernetes/util.go
> +		return err
I think if err is a NotFound error, we need to return nil not err.

2021-11-08 08:54 UTC, rambohe-ch commented
@yanyhui please merge two commits into one commit.

2021-11-09 03:02 UTC, closed without merging